name: Tests

on:
  push:
    branches: [development, staging, production]
    tags:
      - '*.*.*'
  pull_request:
    branches: [development, staging, production]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}

    strategy:
      fail-fast: false
      matrix:
        php: [7.4]
        os: [ubuntu-20.04]
        wordpress: [6.0.2, latest]
        experimental: [false]
#        include:
#          - php: 8.0
#            os: ubuntu-20.04
#            wordpress: latest
#            experimental: true

    name: Tests - PHP ${{ matrix.php }} - WP ${{ matrix.wordpress }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Shutdown Ubuntu MySQL (SUDO)
        run: sudo systemctl stop mysql.service && sudo rm -rf /var/lib/mysql

      - name: Set up MariaDB
        uses: getong/mariadb-action@v1.1
        with:
          mariadb version: 10.5
          mysql root password: root
          mysql user: root
          mysql password: root

      - name: Start required services
        run: mysql --version

      - name: Cache composer packages
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ matrix.php }}-php-${{ hashFiles('**/composer.lock') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer
          coverage: pcov

      - name: Install dependencies
        run: composer install --no-interaction --no-progress

      - name: Install WP tests
        run: bash install-wp-tests.sh wordpress_test root root localhost ${{ matrix.wordpress }}

      - name: Run tests
        run: composer test
        if: matrix.experimental == true

      - name: Run tests with coverage
        run: composer test-coverage
        if: matrix.experimental == false

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
        if: matrix.experimental == false
