name: Tests

on:
  push:
    branches: [development, staging, production]
    tags:
      - '*.*.*'
  pull_request:
    branches: [development, staging, production]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}

#    services:
#      mysql:
#        image: mariadb:10
#        env:
#          MYSQL_USER: root
#          MYSQL_PASSWORD: root
#          MYSQL_ROOT_PASSWORD: root
#        ports:
#          - 3306:3306
#        options: --health-cmd="mysqladmin -uroot -proot ping" --health-interval=10s --health-timeout=10s --health-retries=5

    strategy:
      fail-fast: false
      matrix:
        php: [7.4]
        os: [ubuntu-20.04]
        wordpress: [6.0.2, latest]
        experimental: [false]

#        include:
#          - php: 8.0
#            os: ubuntu-20.04
#            wordpress: latest
#            experimental: true

    name: Tests - PHP ${{ matrix.php }} - WP ${{ matrix.wordpress }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Remove MySQL
        run: sudo apt remove mysql-server-8.0 mysql-common

      - name: Install MariaDB
        run: |
          sudo apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0xF1656F24C74CD1D8
          echo "deb http://downloads.mariadb.com/MariaDB/mariadb-10.5/repo/ubuntu focal main" | sudo tee /etc/apt/sources.list.d/mariadb.list
          sudo apt-get update -o Dir::Etc::sourcelist="sources.list.d/mariadb.list" -o Dir::Etc::sourceparts="-" -o APT::Get::List-Cleanup="0"
          sudo apt-get install mariadb-server-10.5 mariadb-client-10.5

      - name: Start required services
        run: sudo systemctl start mysql && mysql --version

      - name: Cache composer packages
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ matrix.php }}-php-${{ hashFiles('**/composer.lock') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer
          coverage: pcov

      - name: Install dependencies
        run: composer install --no-interaction --no-progress

      - name: Install WP tests
        run: bash install-wp-tests.sh wordpress_test root root localhost:3306 ${{ matrix.wordpress }}

      - name: Run tests
        run: composer test
        if: matrix.experimental == true

      - name: Run tests with coverage
        run: composer test-coverage
        if: matrix.experimental == false

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
        if: matrix.experimental == false
